### PR TITLE
Luastub

### PR DESCRIPTION
**Pull request by Mamietti**
Two different approaches from different sources and yet not a single response. With https://www.google.com/ DoThings() gives "wrong version number" and and with badssl "certificate verify failed".

### CODE REVIEW

**Comment by jviide** [comment]
Background info about the environment that had problems with certificate verification:
- container from ubuntu:16.04 docker image
- `/etc/ssl/certs/ca-certificates.crt` exists

Is this correct, @Mamietti?

**Comment by jviide** [comment]
The **www.google.com** problem might be related to luasocket's handling of 302 redirects (see brunoos/luasec#57). This has been fixed since 2016-03-04 (see diegonehab/luasocket#120, diegonehab/luasocket@5b4b9158).

**Comment by jviide** [comment]
luasec did not support [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) before version 0.6 (released 2016-03-03). `apt-get install lua-sec` seems to currently install luasec version 0.5.1 on Ubuntu 16.04. This could be the reason for the **badssl.com** "certificate verify failed" error.

You can try it out with `openssl s_client` by running:

``` console
$ openssl s_client -connect sha256.badssl.com:443
```

Now enable SNI and try again:

``` console
$ openssl s_client -connect sha256.badssl.com:443 -servername sha256.badssl.com
```

**Comment by Mamietti** [comment]
@jviide Image info correct. I will try those things asap

**Comment by Mamietti** [comment]
Gotta try to get latest luasec as well

**Pull request merged**
