### PR TITLE
Add Python 3 aiohttp TLS client

### PR DESCRIPTION
**Pull request by jwilk**
The default license is OK for me.

### CODE REVIEW

**Comment by ppietikainen** [comment]
Thanks for the submission! 

Running on Fedora 24 (Python 3.5.1 + whatever aiohttp you get with dnf and the latest one from pip) I get:

[pp@the python3-aiohttp]$ python3 run.py wrong.host.badssl.com 443  
Exception in callback None                                                      handle: <Handle cancelled>                                                      Traceback (most recent call last):                                                File "/usr/lib64/python3.5/asyncio/events.py", line 125, in _run                  self._callback(_self._args)                                                   File "/usr/lib64/python3.5/asyncio/selector_events.py", line 671, in _read_ready                                                                                  self._protocol.data_received(data)                                            File "/usr/lib64/python3.5/asyncio/sslproto.py", line 492, in data_received       ssldata, appdata = self._sslpipe.feed_ssldata(data)                           File "/usr/lib64/python3.5/asyncio/sslproto.py", line 200, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.5/ssl.py", line 633, in do_handshake                     match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib64/python3.5/ssl.py", line 296, in match_hostname                   % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'wrong.host.badssl.com' doesn't match either of '_.badssl.com', 'badssl.com'
REJECT

which is ok vs. the stub spec, but could be a bit cleaner? E.g. just the last line of the traceback.

**Comment by jwilk** [comment]
@ppietikainen, I stumbled upon this too, but I don't quite understand what's going on.
My code doesn't do anything to print this traceback. It's `asyncio` that logs it for some reason.
I suspect it's a bug in `aiohttp` or `asyncio`.

**Comment by jwilk** [comment]
According to the `aiohttp` maintainer, this is `asyncio` bug:
https://github.com/python/asyncio/issues/404

**Comment by jdbertron** [comment]
Why are these issues closed. They're not resolved.

**Pull request merged**
