### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by Mamietti**
Just added one .md for the show runner but git exploded so made a pull request instead of direct commit.

### CODE REVIEW

**Comment by ikisusi** [comment]
Files not related to Documentation would get changed as well?

**Comment by ikisusi** [comment]
Now showrunner/README.md starts with "## On-the-fly Certificate Generation". Maybe a separate README-gencerts.md or just reordering the file to start with the most relevant bits and leaving that to the end?

**Comment by Mamietti** [comment]
End sounded good.

**Comment by Mamietti** [comment]
Closes #28

**Pull request merged**
