### PR TITLE
Popularisation: (human) script for getting started.

### PR DESCRIPTION
**Pull request by evilon**
This script has two purposes. 
1. meta: to reflect what is needed for the person with initial interest to try out TryTLS
2. actual: to get started with the getting started documentation.

### CODE REVIEW

**Comment by evilon** [comment]
ping @Mamietti feel free to contribute.

**Comment by Mamietti** [comment]
So person X might be pulled to native and hence it needs an explanation on stubs: how-what-etc. An easy way is to reference the base README, but would it be better to put a short version here as well? Then person Y might be drawn to Docker and he/she probably would want to know what is Docker in the first place. Overall, both in the individual steps and the whole document needs to follow easy-intermediate(1..n)-hard task format.

**Comment by evilon** [comment]
1. **Developers**: already have the environment. They need only runner running, and backend, which can be: 
   1. Backend: trytls.io, badssl, runner's local backend.
   2. If they have evil broken cert idea to test, they can use the backend in docker.
2. **Security researchers**: they take example stubs and throw in a new stub. They will use docker + start a shell in container. (docker hub or docker-file)
3. **End users**: either be ensured from the trytls.io results, or if you need further confirmation, they run it themselves with docker.

**Comment by evilon** [comment]
Switching approach. Recommend merging the first batch now, instead of waiting the whole set to be completed.

**Pull request merged**
