### PR TITLE
Add support for providing context for VERIFY FAILURE etc.

### LINKED ISSUE #86: Add support for providing context for VERIFY FAILURE, UNSUPPORTED etc.
Often it would be helpful for stubs to provide some context why their verdict was VERIFY SUCCESS, VERIFY FAILURE or UNSUPPORTED. Something like this:

``` sh
$ trytls https -- python stubs/python-urllib2/run.py 
platform: OS X 10.11.5
runner: trytls 0.0.8 (CPython 2.7.12, OpenSSL 0.9.8zh)
stub: python 'stubs/python-urllib2/run.py'
 PASS expired certificate [reject expired.badssl.com:443]
 PASS wrong hostname in certificate [reject wrong.host.badssl.com:443]
      output: hostname 'wrong.host.badssl.com' doesn't match either of '*.badssl.com', 'badssl.com'
```

Some possible options:
1. Giving a line of context inline in the verdict. For example the above result could then be achieved by: 
   
   ``` sh
   $ python stubs/python-urllib2/run.py  wrong.host.badssl.com 443
   VERIFY FAILURE hostname 'wrong.host.badssl.com' doesn't match either of '*.badssl.com', 'badssl.com'
   ```
2. Only require stubs to print the verdict (such as VERIFY FAILURE) as their last output line. All lines _before_ that are taken as context and printed. Then the above result could be achieved by printing:
   
   ``` sh
   $ python stubs/python-urllib2/run.py  wrong.host.badssl.com 443
   hostname 'wrong.host.badssl.com' doesn't match either of '*.badssl.com', 'badssl.com'
   VERIFY FAILURE
   ```

### PR DESCRIPTION
**Pull request by jviide**
This pull request adds support for stubs to provide context on why their verdict was `VERIFY SUCCESS`, `VERIFY FAILURE` or `UNSUPPORTED`. The approach is outlined in issue #86.

The stubs are now required to print the verdict (such as `VERIFY SUCCESS`) as their _last_ output line. All lines before that are taken as context and printed:

``` sh
$ trytls https -- python stubs/python-urllib2/run.py 
platform: OS X 10.11.5
runner: trytls 0.0.8 (CPython 2.7.12, OpenSSL 0.9.8zh)
stub: python 'stubs/python-urllib2/run.py'
 PASS expired certificate [reject expired.badssl.com:443]
 PASS wrong hostname in certificate [reject wrong.host.badssl.com:443]
      output: hostname 'wrong.host.badssl.com' doesn't match either of '*.badssl.com', 'badssl.com'
```

Closes #86.

### CODE REVIEW

**Comment by jviide** [comment]
Ping @oherrala, @ikisusi, @nkapu.

**Comment by jviide** [comment]
The other discussed but not implemented discussed way to do this was to allow giving a line of context inline in the verdict. For example the above result could then be achieved by printing `VERIFY FAILURE hostname 'wrong.host.badssl.com' doesn't match either of '*.badssl.com', 'badssl.com'`.

Also both ways could be supported, the inline option becoming a "reason" and the preceding lines becoming "context".

**Comment by oherrala** [comment]
Quite beautiful.

``` console
$ trytls https -- stack exec test-wreq
platform: OS X 10.11.5
runner: trytls 0.0.8 (CPython 2.7.12, OpenSSL 0.9.8zh)
stub: stack exec 'test-wreq'
 PASS expired certificate [reject expired.badssl.com:443]
      output: HandshakeFailed (Error_Protocol ("certificate has expired",True,CertificateExpired))
 FAIL wrong hostname in certificate [reject wrong.host.badssl.com:443]
 PASS self-signed certificate [reject self-signed.badssl.com:443]
      output: HandshakeFailed (Error_Protocol ("certificate rejected: [SelfSigned]",True,CertificateUnknown))
 PASS SHA-256 signature [accept sha256.badssl.com:443]
 PASS 1000 subjectAltNames [accept 1000-sans.badssl.com:443]
 PASS incomplete chain of trust [reject incomplete-chain.badssl.com:443]
      output: HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa))
 PASS Superfish CA [reject superfish.badssl.com:443]
      output: HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa))
 PASS eDellRoot CA [reject edellroot.badssl.com:443]
      output: HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa))
 PASS DSDTestProvider CA [reject dsdtestprovider.badssl.com:443]
      output: HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa))
 PASS protect against an OS X vulnerability [reject www.ssllabs.com:10443]
      output: HandshakeFailed (Error_Protocol ("bad SignatureRSA for ecdhparams",True,HandshakeFailure))
 PASS protect against the FREAK attack [reject www.ssllabs.com:10444]
      output: HandshakeFailed (Error_Packet_Parsing "handshake[HandshakeType_ServerKeyXchg]: parsing error: remaining bytes")
 FAIL protect against the Logjam attack [reject www.ssllabs.com:10445]
 SKIP valid localhost certificate [accept localhost:53964]
 SKIP invalid localhost certificate [reject localhost:53965]
 SKIP use only the given CA bundle, not system's [reject sha256.badssl.com:443]
```

**Comment by jviide** [comment]
I guess this PR has gotten some traction, so I'll remove the [WIP] marker.

**Comment by oherrala** [comment]
I suggest this to be merged ASAP to get maximum testing (and stub support) before 0.2.0 release.

**Pull request merged**
